import HomePage from "@/components/NavBar";
import "./globals.css";
import WhatappFloatingBtn from "@/components/WhatsAppBtn";
import Footer from "@/components/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <HomePage />
        {children}
        <WhatappFloatingBtn />
        <Footer />
      </body>
    </html>
  );
}
